name: UNIT tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install depedencies
        run: npm install

      - name: run tests
        run: npm test
